/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.management;

import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleConnection;

/**
 *
 * @author crazy
 */
public class BangDiem extends javax.swing.JFrame {

    /**
     * Creates new form BangDiem
     */
    public BangDiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lableBangdiem = new javax.swing.JLabel();
        lableDKHP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        lblDoB = new javax.swing.JLabel();
        lbl_cbSemester = new javax.swing.JLabel();
        txtbox_fullname = new javax.swing.JTextField();
        txtbox_id = new javax.swing.JTextField();
        txtbox_dob = new javax.swing.JTextField();
        txtbox_gender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbScore = new javax.swing.JTable();
        cbSemester = new javax.swing.JComboBox<>();
        lblGender1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                loadBangdiem_userInfo(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(25, 181, 254));

        lableBangdiem.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lableBangdiem.setForeground(new java.awt.Color(250, 250, 250));
        lableBangdiem.setText("Bảng Điểm");

        lableDKHP.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lableDKHP.setForeground(new java.awt.Color(250, 250, 250));
        lableDKHP.setText("Đăng Ký Học Phần");
        lableDKHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableDKHPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lableDKHP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lableBangdiem)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableBangdiem)
                    .addComponent(lableDKHP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 780, 60);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        lblName.setText("Họ và Tên:");

        lblStudentID.setText("Mã Số Sinh Viên:");

        lblDoB.setText("Ngày sinh:");

        lbl_cbSemester.setText("Bảng Điểm:");

        txtbox_fullname.setEditable(false);
        txtbox_fullname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbox_fullname.setText("Dương Quốc Cường");
        txtbox_fullname.setEditable(false);

        txtbox_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbox_id.setText("jTextField2");
        txtbox_id.setEditable(false);

        txtbox_dob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbox_dob.setText("jTextField2");
        txtbox_dob.setEditable(false);

        txtbox_gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtbox_gender.setText("jTextField2");
        txtbox_gender.setEditable(false);

        tbScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Mã HP", "Tên học phần", "Tín chỉ", "Điểm QT", "Điểm GK	", "Điểm TH	", "Điểm CK	", "Điểm HP	"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbScore.setRowHeight(30);
        jScrollPane1.setViewportView(tbScore);
        if (tbScore.getColumnModel().getColumnCount() > 0) {
            tbScore.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbScore.getColumnModel().getColumn(1).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbScore.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(4).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(5).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(6).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(7).setPreferredWidth(40);
            tbScore.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1" }));
        cbSemester.setToolTipText("");
        cbSemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSemesterItemStateChanged(evt);
            }
        });

        lblGender1.setText("Giới Tính");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(lbl_cbSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbox_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txtbox_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbox_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbox_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbox_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 140, 780, 550);

        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout);
        btn_logout.setBounds(643, 100, 100, 40);

        setBounds(0, 0, 795, 681);
    }// </editor-fold>//GEN-END:initComponents

    private void cbSemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSemesterItemStateChanged
        // TODO add your handling code here:
        String semester = (String) cbSemester.getSelectedItem();
        this.prepareGUI_tbScore(semester);
    }//GEN-LAST:event_cbSemesterItemStateChanged

    //load view dang ki hoc phan
    private void lableDKHPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableDKHPMouseClicked

        this.dispose();
        DangKyHP dkhp = new DangKyHP();
        dkhp.setVisible(true);
        dkhp.prepareUI_panelDangKyHP();
        dkhp.prepareUI_panelThongTin();
    }//GEN-LAST:event_lableDKHPMouseClicked

    private void loadBangdiem_userInfo(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadBangdiem_userInfo

        //load user info
        String getUserInfoStringSQL = "select fullname,studentid,dateofbirth,gender from student,users where student.STUDENTID = users.USERID and studentid = '" + CONST.currentUserid + "'";

        DBConnection connection = new DBConnection();

        connection.connect();

        try {

            ResultSet result = connection.query(getUserInfoStringSQL);
            if (result.next()) {
                txtbox_fullname.setText(result.getString("fullname"));
                txtbox_dob.setText(result.getString("dateofbirth"));
                txtbox_gender.setText(result.getString("gender"));
                txtbox_id.setText(result.getString("studentid"));
            }
        } catch (Exception e) {

            System.out.println("err load user info " + e);
        }

        connection.disconnect();

        //load bang diem
        prepareGUI_cbSemester();
        String semester = (String) CbSemester.getSelectedItem();
        prepareGUI_tbScore(semester);
    }//GEN-LAST:event_loadBangdiem_userInfo

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        CONST.loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public void prepareGUI_cbSemester() {
        model_cbSemester = (DefaultComboBoxModel<String>) this.cbSemester.getModel();
        model_cbSemester.removeAllElements();
        String userID = CONST.currentUserid;
        try {

            connection.connect();
            PreparedStatement ps = DBConnection.con.prepareCall("SELECT semester FROM Bangdiem WHERE STUDENTID = ?");
            ps.setString(1, userID);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model_cbSemester.addElement(rs.getString(1));
            }
            connection.disconnect();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void prepareGUI_tbScore(String semester) {
        model_tbScore = (DefaultTableModel) this.tbScore.getModel();
        model_tbScore.setRowCount(0);
        String userID = CONST.currentUserid;
        int stt = 1;
        double averageScore = 0;
        int sumNumberOfCredits = 0;
        try {
            connection.connect();
            String stringSQL = "SELECT SubjectID, SubjectName,NumberOfCredits,DiemQT,DiemGK,DiemTH,DiemCK,Score FROM Bangdiem bd,DIEMMONHOC dmh, SUBJECT s WHERE STUDENTID = ? AND bd.ID_BANGDIEM = dmh.ID_BANGDIEM AND bd.SEMESTER = ? AND s.SUBJECTID = dmh.ID_MONHOC";
            PreparedStatement ps = DBConnection.con.prepareCall(stringSQL);
            ps.setString(1, userID);
            ps.setString(2, semester);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String subjectID = rs.getString(1);
                String subjectName = rs.getString(2);
                int numberOfCredits = rs.getInt(3);
                double diemQT = rs.getDouble(4);
                double diemGK = rs.getDouble(5);
                double diemTH = rs.getDouble(6);
                double diemCK = rs.getDouble(7);
                double score = rs.getDouble(8);
                model_tbScore.addRow(new Object[]{stt, subjectID, subjectName, numberOfCredits, diemQT, diemGK, diemTH, diemCK, score});
                stt++;
                sumNumberOfCredits += numberOfCredits;
                averageScore += score / numberOfCredits;
            }
            averageScore = Math.round(averageScore * 100.0) / 100.0;
            if (model_tbScore.getRowCount() > 0) {
                model_tbScore.addRow(new Object[]{null, null, "Trung bình học kỳ", sumNumberOfCredits, null, null, null, null, averageScore});
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BangDiem scoreTable = new BangDiem();
//                scoreTable.setVisible(true);
//                scoreTable.prepareGUI_cbSemester();
//                String semester = (String) scoreTable.CbSemester.getSelectedItem();
//                scoreTable.prepareGUI_tbScore(semester);
//            }
//        });
//    }
    public javax.swing.JComboBox<String> CbSemester;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableBangdiem;
    private javax.swing.JLabel lableDKHP;
    private javax.swing.JLabel lblDoB;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lbl_cbSemester;
    private javax.swing.JTable tbScore;
    private javax.swing.JTextField txtbox_dob;
    private javax.swing.JTextField txtbox_fullname;
    private javax.swing.JTextField txtbox_gender;
    private javax.swing.JTextField txtbox_id;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel<String> model_cbSemester;
    private DefaultTableModel model_tbScore;
    private DBConnection connection = new DBConnection();
}
