package student.management;

import com.google.gson.Gson;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class QL_User extends javax.swing.JFrame {

    User[] allUsers;

    /**
     * Creates new form QL_User
     */
    void myCustomInit() {
        tableUsers.setDefaultEditor(Object.class, null);
        ListSelectionModel cellSelectionModel = tableUsers.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener((ListSelectionEvent e) -> {

            int[] selectedRow = tableUsers.getSelectedRows();
            //String a =(String)tableUsers.getValueAt(1, 1);
            String selectedUsername = (String) tableUsers.getValueAt(selectedRow[0], 0);
            CONST.choosingUsername = selectedUsername;

        });
    }

    public QL_User() {
        initComponents();
        myCustomInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_createAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_detail = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                userManagementFormActived(evt);
            }
        });

        btn_createAccount.setText("Tạo tài khoản");
        btn_createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createAccountActionPerformed(evt);
            }
        });

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "Chức Vụ", "Hành Động"
            }
        ));
        jScrollPane1.setViewportView(tableUsers);

        jLabel3.setText("Phần mềm quản lý sinh viên");

        btn_detail.setText("Xem chi tiết");
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });

        btn_Delete.setText("Xóa");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(btn_createAccount))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(414, Short.MAX_VALUE)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_createAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(239, Short.MAX_VALUE)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void clearTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tableUsers.getModel();
            dtm.setRowCount(0);

        } catch (Exception e) {
            System.out.println("errror clear table");
            System.out.println(e);
        }

    }

    //form open event
    private void userManagementFormActived(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_userManagementFormActived
        loadAllUserToTable();

    }//GEN-LAST:event_userManagementFormActived

    private void btn_createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createAccountActionPerformed
        new signupForm().setVisible(true);
    }//GEN-LAST:event_btn_createAccountActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        try {

            DBConnection connection = new DBConnection();
            connection.connect();

            PreparedStatement query = DBConnection.con.prepareStatement("delete from users where username=?");
            query.setString(1, CONST.choosingUsername);

            query.execute();

            connection.disconnect();
            JOptionPane.showMessageDialog(null, "Xóa thành công !");

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Lỗi xảy ra, vui lòng thử lại sau !");
        }


    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        CONST.loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        try {

            DBConnection connection = new DBConnection();
            connection.connect();

            PreparedStatement query = DBConnection.con.prepareStatement("select gender,dateofbirth, userid,username,fullname,userrole,address,email,phonenumber from users where username=?");
            query.setString(1, CONST.choosingUsername);

            ResultSet result = query.executeQuery();

            if (result.next()) {

                signupForm userDetail = new signupForm();
                userDetail.setTxtbox_address(result.getString("address"));
                userDetail.setTxtbox_id(result.getString("userid"));
                userDetail.setTxtbox_dob(result.getString(2));
                userDetail.setTxtbox_email(result.getString("email"));
                userDetail.setTxtbox_fullname(result.getString("fullname"));
                //userDetail.setTxtbox_gender(result.getString("gender"));
                userDetail.setTxtbox_phone(result.getString("phonenumber"));
                userDetail.setTxtbox_role(result.getString("userrole"));
                userDetail.setTxtbox_username(result.getString("username"));
                userDetail.setTxtbox_password("****");
                userDetail.disableAllInput();

                userDetail.setVisible(true);

            }

            connection.disconnect();
            
        } catch (Exception e) {
            System.out.println("view user's detail error");
            System.out.println(e);
        }

    }//GEN-LAST:event_btn_detailActionPerformed
    void loadAllUserToTable() {
        clearTable();

        DBConnection connection = new DBConnection();

        try {
            connection.connect();
            PreparedStatement query = DBConnection.con.prepareStatement("select username,rolename from users,role where users.userrole=role.roleid");
            ResultSet result = query.executeQuery();
            while (result.next()) {
                DefaultTableModel model = (DefaultTableModel) tableUsers.getModel();
                model.addRow(new Object[]{
                    result.getString(1),
                    result.getString(2)
                });
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        connection.disconnect();
//        for (int i = 0; i < allUsers.length; i++) {
//            DefaultTableModel model = (DefaultTableModel) tableUsers.getModel();
//            model.addRow(new Object[]{
//                i + 1,
//                allUsers[i].username,
//                allUsers[i].roles
//
//            });
//        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_createAccount;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
