/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.management;

import javax.swing.*;
import java.sql.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crazy
 */
public class QuanLyDiem extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDiem
     */
    public QuanLyDiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSubject = new javax.swing.JTable();
        cbSemester = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_titleOfferingName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtDiemQT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiemGK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiemTH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiemCK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblOfferingName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lblErrorNotification = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        lableName = new javax.swing.JLabel();
        lableID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(835, 630));
        setSize(new java.awt.Dimension(835, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                loadSubject(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(25, 181, 254));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Danh Sách Môn Học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(835, 620));

        jLabel2.setText("Họ và Tên:");

        jLabel3.setText("Mã Giảng Viên:");

        jTabbedPane1.setBackground(new java.awt.Color(250, 250, 250));

        jPanel5.setBackground(new java.awt.Color(250, 250, 250));

        tbSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Môn Học", "Mã Học Phần"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSubjectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSubject);

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSemesterItemStateChanged(evt);
            }
        });

        jLabel4.setText("Học Kỳ - Năm Học:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Môn Học", jPanel5);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));

        lbl_titleOfferingName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_titleOfferingName.setText("Lớp:");

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MSSV", "Tên Sinh Viên", "Điểm QT", "Điểm GK", "Điểm TH", "Điểm CK", "Điểm HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStudent.setRowHeight(20);
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbStudent);
        if (tbStudent.getColumnModel().getColumnCount() > 0) {
            tbStudent.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbStudent.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbStudent.getColumnModel().getColumn(2).setPreferredWidth(180);
            tbStudent.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbStudent.getColumnModel().getColumn(4).setPreferredWidth(30);
            tbStudent.getColumnModel().getColumn(5).setPreferredWidth(30);
            tbStudent.getColumnModel().getColumn(6).setPreferredWidth(30);
            tbStudent.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        jLabel5.setText("Họ và Tên:");

        txtStudentName.setEditable(false);

        txtDiemQT.setEditable(false);

        jLabel6.setText("Điểm QT");

        txtDiemGK.setEditable(false);

        jLabel7.setText("Điểm GK");

        txtDiemTH.setEditable(false);

        jLabel8.setText("Điểm TH");

        txtDiemCK.setEditable(false);

        jLabel9.setText("Điểm CK");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblOfferingName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setText("MSSV:");

        txtStudentID.setEditable(false);

        lblErrorNotification.setBackground(new java.awt.Color(235, 151, 78));
        lblErrorNotification.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblErrorNotification.setForeground(new java.awt.Color(102, 102, 102));
        lblErrorNotification.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_titleOfferingName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOfferingName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiemTH, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentID))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titleOfferingName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfferingName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDiemTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnClear))
                        .addGap(18, 18, 18)
                        .addComponent(lblErrorNotification)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh Sách Sinh Viên", jPanel4);

        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        lableName.setText("jLabel11");

        lableID.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(118, 118, 118))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lableName))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lableID))))
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1000, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSubjectMouseClicked
        // TODO add your handling code here:
        int rowSelected = tbSubject.getSelectedRow();
        v_OfferingID = (String) tbSubject.getModel().getValueAt(rowSelected, 1);
        String semester = (String) cbSemester.getSelectedItem();
        String lectureID = CONST.currentUserid;
        //System.out.println(v_OfferingID+semester+lectureID);
        this.loadData_tbStudent(v_OfferingID, semester, lectureID);
        jTabbedPane1.setSelectedIndex(1);
        lblOfferingName.setText(v_OfferingID);
    }//GEN-LAST:event_tbSubjectMouseClicked

    private void cbSemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSemesterItemStateChanged
        // TODO add your handling code here:
        String semester = (String) cbSemester.getSelectedItem();
        this.prepareUI_tbSubject(semester);
        clearTxtField();
        model_tbStudent = (DefaultTableModel) tbStudent.getModel();
        model_tbStudent.setRowCount(0);
    }//GEN-LAST:event_cbSemesterItemStateChanged

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearTxtField();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String studentID = txtStudentID.getText();
        Double diemQT = Double.parseDouble(txtDiemQT.getText());
        Double diemGK = Double.parseDouble(txtDiemGK.getText());
        Double diemTH = Double.parseDouble(txtDiemTH.getText());
        Double diemCK = Double.parseDouble(txtDiemCK.getText());
        String lectureID = CONST.currentUserid;
        String semester = (String) cbSemester.getSelectedItem();
        lblErrorNotification.setText("");
        try {
            connection.connect();
            CallableStatement cstm = DBConnection.con.prepareCall("{call Update_diem(?,?,?,?,?,?,?,?)}");
            cstm.setString(1, studentID);
            cstm.setString(2, semester);
            cstm.setString(3, v_OfferingID);
            cstm.setString(4, lectureID);
            cstm.setDouble(5, diemQT);
            cstm.setDouble(6, diemGK);
            cstm.setDouble(7, diemTH);
            cstm.setDouble(8, diemCK);
            cstm.executeQuery();
            loadData_tbStudent(v_OfferingID, semester, lectureID);
            clearTxtField();
        } catch (SQLException e) {
            System.out.println(e);
            if (e.getErrorCode() == 20007) {
                lblErrorNotification.setText("<html><p style=\"padding:6 8; font-size:11\">Cập nhật điểm không thành công<br></p></html>");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked
        // TODO add your handling code here:
        int row = tbStudent.getSelectedRow();
        String studentID = (String) tbStudent.getValueAt(row, 1);
        String studentName = (String) tbStudent.getValueAt(row, 2);
        double diemQT = Double.parseDouble(tbStudent.getValueAt(row, 3).toString());
        double diemGK = Double.parseDouble(tbStudent.getValueAt(row, 4).toString());
        double diemTH = Double.parseDouble(tbStudent.getValueAt(row, 5).toString());
        double diemCK = Double.parseDouble(tbStudent.getValueAt(row, 6).toString());
        loadData_txtField(studentID, studentName, diemQT, diemGK, diemTH, diemCK);
    }//GEN-LAST:event_tbStudentMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        CONST.loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    //load subject and user info
    private void loadSubject(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadSubject

        //load user info
        String getUserInfoStringSQL = "select fullname from users where userid = '" + CONST.currentUserid + "'";

        DBConnection connection = new DBConnection();

        connection.connect();

        try {

            ResultSet result = connection.query(getUserInfoStringSQL);

            if (result.next()) {

                lableName.setText(result.getString("fullname"));
                lableID.setText(CONST.currentUserid);
            }

        } catch (Exception e) {

            System.out.println("err load user info " + e);
        }

        connection.disconnect();

        //load subject
        prepareUI_tbSemester();
        String semester = (String) cbSemester.getSelectedItem();
        prepareUI_tbSubject(semester);
    }//GEN-LAST:event_loadSubject
    private void loadData_txtField(String studentID, String studentName, double diemQT, double diemGK, double diemTH, double diemCK) {
        txtStudentID.setText(studentID);
        txtStudentName.setText(studentName);
        txtDiemQT.setText(String.valueOf(diemQT));
        txtDiemGK.setText(String.valueOf(diemGK));
        txtDiemTH.setText(String.valueOf(diemTH));
        txtDiemCK.setText(String.valueOf(diemCK));

        txtDiemQT.setEditable(true);
        txtDiemGK.setEditable(true);
        txtDiemTH.setEditable(true);
        txtDiemCK.setEditable(true);
    }

    private void clearTxtField() {
        txtStudentID.setText("");
        txtStudentName.setText("");
        txtDiemQT.setText("");
        txtDiemGK.setText("");
        txtDiemTH.setText("");
        txtDiemCK.setText("");

        txtStudentID.setEditable(false);
        txtStudentName.setEditable(false);
        txtDiemQT.setEditable(false);
        txtDiemGK.setEditable(false);
        txtDiemTH.setEditable(false);
        txtDiemCK.setEditable(false);
    }

    /**
     * @param offeringID
     * @param semester
     * @param lectureID
     */
    private void loadData_tbStudent(String offeringID, String semester, String lectureID) {
        int STT = 1;
        String studentID, studentName;
        Double diemQT, diemGK, diemTH, diemCK, diemHP;
        model_tbStudent = (DefaultTableModel) tbStudent.getModel();
        model_tbStudent.setRowCount(0);
        try {
            connection.connect();
            String sql = "SELECT studentID,userName,dmh.DIEMQT,dmh.DIEMGK,dmh.DIEMTH,dmh.DIEMCK,dmh.Score FROM USERS U, BANGDIEM bd, DIEMMONHOC dmh WHERE bd.ID_BANGDIEM = dmh.ID_BANGDIEM AND bd.STUDENTID = U.USERID AND bd.SEMESTER = ? AND dmh.CREATEDBY = ? AND dmh.ID_MONHOC = (SELECT subjectID FROM OFFering WHERE offeringID = ?)";
            PreparedStatement ps = DBConnection.con.prepareStatement(sql);
            ps.setString(1, semester);
            ps.setString(2, lectureID);
            ps.setString(3, offeringID);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                studentID = rs.getString(1);
                studentName = rs.getString(2);
                diemQT = rs.getDouble(3);
                diemGK = rs.getDouble(4);
                diemTH = rs.getDouble(5);
                diemCK = rs.getDouble(6);
                diemHP = rs.getDouble(7);
                model_tbStudent.addRow(new Object[]{STT, studentID, studentName, diemQT, diemGK, diemTH, diemCK, diemHP});
                STT++;
            }
            connection.disconnect();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void prepareUI_tbSemester() {
        model_cbSemester = (DefaultComboBoxModel<String>) this.cbSemester.getModel();
        model_cbSemester.removeAllElements();
        String lectureID = CONST.currentUserid;
        try {
            connection.connect();
            PreparedStatement ps = DBConnection.con.prepareCall("SELECT semester FROM OFFERING o WHERE o.LECTUREID = ? GROUP BY semester");
            ps.setString(1, lectureID);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model_cbSemester.addElement(rs.getString(1));
            }
            connection.disconnect();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void prepareUI_tbSubject(String semester) {
        try {
            connection.connect();
            String offeringID, subjectName;
            String lectureID = CONST.currentUserid;
            String sql = "SELECT offeringID, subjectName FROM OFFERING o, SUBJECT s WHERE o.LECTUREID = ? AND o.SUBJECTID = s.SUBJECTID AND o.Semester = ?";
            PreparedStatement ps = DBConnection.con.prepareCall(sql);
            ps.setString(1, lectureID);
            ps.setString(2, semester);
            ResultSet rs = ps.executeQuery();
            model_tbSubject = (DefaultTableModel) tbSubject.getModel();
            model_tbSubject.setRowCount(0);
            while (rs.next()) {
                offeringID = rs.getString(1);
                subjectName = rs.getString(2);
                System.out.println(offeringID);
                System.out.println(subjectName);
                model_tbSubject.addRow(new Object[]{subjectName, offeringID});
            }
            connection.disconnect();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QuanLyDiem qld = new QuanLyDiem();
                qld.setVisible(true);
                qld.prepareUI_tbSemester();
                String semester = (String) qld.cbSemester.getSelectedItem();
                qld.prepareUI_tbSubject(semester);
                //qld.addEvent_tbScore();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lableID;
    private javax.swing.JLabel lableName;
    private javax.swing.JLabel lblErrorNotification;
    private javax.swing.JLabel lblOfferingName;
    private javax.swing.JLabel lbl_titleOfferingName;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTable tbSubject;
    private javax.swing.JTextField txtDiemCK;
    private javax.swing.JTextField txtDiemGK;
    private javax.swing.JTextField txtDiemQT;
    private javax.swing.JTextField txtDiemTH;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
    private DBConnection connection = new DBConnection();
    private DefaultTableModel model_tbSubject;
    private DefaultComboBoxModel model_cbSemester;
    private DefaultTableModel model_tbStudent;
    private String v_OfferingID;
}
